Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.network "public_network"
    
    # Sincronizar el directorio actual (contiene install-v3.sh) con /vagrant en la VM
    config.vm.synced_folder ".", "/vagrant"

    # Pasar parámetros al script
    config.vm.provision "shell", inline: <<-SHELL
      cat -A /vagrant/config.ini
      #/vagrant/install.sh -u admin -p pass
      /vagrant/install-v2.sh -f /vagrant/config.ini
      #/vagrant/install-v2.sh -u user1 -p user1
      #/vagrant/uninstall.sh
    SHELL
  end
  