Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.network "public_network"
    
    # Pasar parámetros al script
    config.vm.provision "shell", inline: <<-SHELL
      #/vagrant/install.sh -u admin -p pass
      /vagrant/install-v2.sh -f /vagrant/config.ini
      #/vagrant/uninstall.sh
    SHELL
  end
  